### ISSUE TITLE
MobGriefing module not preventing creepers from causing craters on latest build on 1.18.1

### ISSUE THREAD

**Issue by JAladwan** [MC-Machinations/VanillaTweaks#52]
Tested twice with the module enabled and disabled, did not seem to prevent creepers from causing craters. Did not test Endermen or Ghasts, though.

Only other plugins I have on my server are sleepmost and simpleTPA. 

Working around this by just using the datapacks from Vanilla Tweaks itself, but hoping this can be fixed eventually as I try my best to cut down on the usage of datapacks on my server.

**Comment by jscott3201** [comment]
`plugins/VanillaTweaks/modules.yml`

```yaml
mobs:
  count-mob-deaths: false
  larger-phantoms: false
  mob-griefing: true
```

`plugins/VanillaTweaks/modules/mobgriefing/config.yml`

Check you have this:

```yaml
# Prevents enderman from picking up blocks
anti-enderman-grief: true
anti-ghast-grief: true
anti-creeper-grief: true
# When enabled both block and entity damage will be cancelled for creeper and ghast fireball explosions. 
# Disable to turn on entity damage for those explosions
disable-entity-damage: false
```

I had this same issue just setting it to true. I am running the latest Paper build and have had no issues for a few weeks running this
